# Generated by Django 2.1.4 on 2020-05-13 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeToAccess',
            fields=[
                ('CAID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='CA')),
                ('CODE', models.CharField(blank=True, max_length=100, null=True, verbose_name='Code')),
                ('ACCESS_TOKEN', models.CharField(blank=True, max_length=100, null=True, verbose_name='Access')),
                ('OPEN_ID', models.CharField(blank=True, max_length=100, null=True, verbose_name='OpenID')),
            ],
            options={
                'verbose_name': '06_code_access_table',
                'verbose_name_plural': '06_code_access_table',
                'db_table': '06_code_access_table',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesstoken', models.CharField(default='', max_length=255, verbose_name='微信 access_token')),
                ('openid', models.CharField(default='', max_length=32, verbose_name='微信 openid')),
                ('nickname', models.CharField(default='', max_length=256, verbose_name='微信昵称')),
                ('wsex', models.CharField(default='', max_length=3, verbose_name='微信性别')),
                ('province', models.CharField(default='', max_length=50, verbose_name='微信省份')),
                ('city', models.CharField(default='', max_length=50, verbose_name='微信城市')),
                ('country', models.CharField(default='', max_length=50, verbose_name='微信国家')),
                ('headimgurl', models.CharField(default='', max_length=200, verbose_name='微信头像')),
                ('privilege', models.CharField(default='', max_length=3, verbose_name='微信权限')),
                ('unionid', models.CharField(default='', max_length=32, verbose_name='微信 unionid')),
                ('refresh_token', models.CharField(default='', max_length=512, verbose_name='微信 refresh_token')),
                ('refresh_token_time', models.IntegerField(default=0)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Fitness.Member')),
            ],
            options={
                'verbose_name': '00_user_table',
                'verbose_name_plural': '00_user_table',
                'db_table': '00_user_table',
            },
        ),
    ]
