# Generated by Django 3.0.6 on 2020-05-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0002_codetoaccess_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepay_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='预支付交易会话标识')),
                ('out_trade_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='商户订单号')),
                ('transaction_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='微信支付订单号')),
                ('bank_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='付款银行')),
                ('cash_fee', models.IntegerField(blank=True, null=True, verbose_name='现金支付金额')),
                ('time_end', models.DateTimeField(blank=True, null=True, verbose_name='支付完成时间')),
                ('busname', models.CharField(blank=True, max_length=16, null=True, verbose_name='业务')),
                ('description', models.TextField(verbose_name='商品描述')),
                ('total_fee', models.IntegerField(help_text='订单总金额，单位分', verbose_name='订单总金额')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '07_Order_table',
                'verbose_name_plural': '07_Order_table',
                'db_table': '07_Order_table',
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='PHOTO',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='头像'),
        ),
    ]
