# Generated by Django 3.0.6 on 2020-05-24 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0003_auto_20200518_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='OPENID',
            field=models.CharField(default='', max_length=64, verbose_name='微信openid'),
        ),
        migrations.AddField(
            model_name='order',
            name='good_id',
            field=models.IntegerField(verbose_name='商品id'),
        ),
        migrations.AddField(
            model_name='order',
            name='open_id',
            field=models.CharField(max_length=64, verbose_name='用户微信openid'),
        ),
        migrations.AlterField(
            model_name='codetoaccess',
            name='ACCESS_TOKEN',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Access'),
        ),
        migrations.AlterField(
            model_name='member',
            name='CARD_ID',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Fitness.Card', verbose_name='卡ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='COURSE_ID',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Fitness.Course', verbose_name='课程ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='PHONE',
            field=models.CharField(blank=True, default='0', max_length=100, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='member',
            name='PICTURE',
            field=models.ImageField(blank=True, default='0', null=True, upload_to='picture/', verbose_name='人脸照片'),
        ),
        migrations.AlterField(
            model_name='member',
            name='REMAIN_TIME',
            field=models.CharField(blank=True, default='0', max_length=100, null=True, verbose_name='会员剩余时间'),
        ),
        migrations.AlterField(
            model_name='member',
            name='SHARE',
            field=models.CharField(blank=True, default='0', max_length=100, null=True, verbose_name='我的分享'),
        ),
        migrations.AlterField(
            model_name='member',
            name='YIBI',
            field=models.CharField(blank=True, default='0', max_length=100, null=True, verbose_name='我的易币'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='accesstoken',
            field=models.CharField(default='', max_length=512, verbose_name='微信 access_token'),
        ),
    ]
