# Generated by Django 3.0.6 on 2020-05-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0004_auto_20200524_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='VERIFICATION_CODE',
            field=models.CharField(default='', max_length=64, verbose_name='验证码'),
        ),
        migrations.AddField(
            model_name='member',
            name='VERIFICATION_CODE_IN_DATE',
            field=models.DateTimeField(default=None, verbose_name='验证码有效时间'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='jsapi_ticket',
            field=models.CharField(default=None, max_length=512, verbose_name='微信 jsapi_ticket'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscribe',
            field=models.IntegerField(default=0, verbose_name='公众号关注状态'),
        ),
    ]
